### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by zzj1213** [patternfly-java/showcase#1]
[ERROR] Failed to execute goal on project patternfly-showcase: Could not resolve dependencies for project org.patternfly:patternfly-showcase:gwt-app:2.43.1: 

Failed to collect dependencies at org.gwtproject.i18n:gwt-datetimeformat:jar:1.0-SNAPSHOT: 

Failed to read artifact descriptor for org.gwtproject.i18n:gwt-datetimeformat:jar:1.0-SNAPSHOT:

Could not transfer artifact org.gwtproject.i18n:gwt-datetimeformat:pom:1.0-SNAPSHOT from/to vertispan-gwt-snapshots (https://repo.vertispan.com/gwt-snapshot/): 

Transfer failed for 

https://repo.vertispan.com/gwt-snapshot/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/gwt-datetimeformat-1.0-SNAPSHOT.pom: 

**gwt-datetimeformat-1.0-SNAPSHOT.pom** could not be found on the path:  https://repo.vertispan.com/gwt-snapshot/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/

**Comment by hpehl** [comment]
Should be fixed now
